Repository zalando/zalando.github.io, pull requests merged in 2018-06, with the labels that each got.

#136 DOCS removed from header
  _includes/footer.html
  _includes/header.html
Labels: Website

#137 Removed banner for docs
  _layouts/default.html
  _layouts/documentation.html
  assets/css/article.css
  assets/css/main.css
Labels: Website

#143 Landing template for blog
  _config.yml
  _includes/header.html
  _includes/pagination.html
  _includes/recent-posts.html
  _layouts/landing.html
  _posts/2018-01-11-faces-of-fashion-mnist.md
  assets/css/article.css
  assets/css/blog.css
  assets/css/main.css
  blog/index.html
Labels: e: Community

#150 Adding Gemfile.lock for security checking by GH.com
  .gitignore
  Gemfile.lock
Labels: e: Community, pr: Needs Review

#134 Documents on releasing, using and contributing upstream
  .gitignore
  Gemfile
  _config.yml
  _docs/index.md
  _docs/releasing/contributions.md
  _docs/releasing/github.md
  _docs/releasing/incubation.md
  _docs/releasing/index.md
  _docs/releasing/license.md
  _docs/resources/licensing.md
  _docs/resources/open-source-guild.md
  _docs/resources/open-source-review-group.md
  _docs/resources/open-source-team.md
  _docs/resources/teams-groups.md
  _docs/using/contributing.md
  _docs/using/how-to-oss.md
  _docs/using/index.md
  _docs/using/rules-of-play.md
  _includes/docs-list.html
  _includes/header.html
  _layouts/documentation.html
  _pages/index.md
  assets/css/article.css
Labels: pr: Work In Progress

#169 WIP: More docs content review
  _docs/releasing/index.md
  _docs/resources/licensing.md
Labels: pr: Work In Progress
