Repository zalando/zalando.github.io, pull requests merged in 2018-05, with the labels that each got.

#63 Projects page
  docs/assets/css/main.css
  docs/assets/img/laptop.jpg
  docs/assets/js/config.js
  docs/assets/js/index.js
  docs/assets/js/project.js
  docs/assets/js/store.js
  docs/assets/svg/fork.svg
  docs/assets/svg/languages/CSS.svg
  docs/assets/svg/languages/Clojure.svg
  docs/assets/svg/languages/Elm.svg
  docs/assets/svg/languages/Kotlin.svg
  docs/assets/svg/languages/Shell.svg
  docs/assets/svg/star.svg
  docs/assets/svg/user.svg
  docs/components/filterLabel.js
  docs/components/filterOption.js
  docs/components/footer.js
  docs/components/header.js
  docs/components/loadMoreProjects.js
  docs/components/project.js
  docs/components/statistic.js
  docs/components/user.js
  docs/index.html
  docs/projects/index.html
Labels: e: Yak Shaving, pr: Work In Progress, website

#106 Start of the infrastructure for hosting articles on the site
  _config.yml
  _includes/banner.html
  _includes/header.html
  _includes/history.html
  _includes/recent-posts.html
  _includes/sharing.html
  _layouts/article.html
  _layouts/default.html
  _pages/index.md
  _posts/2017-08-30-innersource-do-dont.md
  _posts/2017-10-17-small-pull-requests.md
  _posts/2018-01-11-faces-of-fashion-mnist.md
  _posts/2018-02-22-zalando-at-fosdem.md
  assets/assets/css/main.css
  assets/assets/img/laptop.jpg
  assets/assets/img/zalando-logo.png
  assets/assets/img/zalando-people.jpg
  assets/assets/img/zalando.ico
  assets/assets/js/config.js
  assets/assets/js/index.js
  assets/assets/js/store.js
  assets/assets/svg/fork.svg
  assets/assets/svg/gg.svg
  assets/assets/svg/handshake-o.svg
  assets/assets/svg/languages/CSS.svg
  assets/assets/svg/languages/Clojure.svg
  assets/assets/svg/languages/Elm.svg
  assets/assets/svg/languages/Go.svg
  assets/assets/svg/languages/Java.svg
  assets/assets/svg/languages/JavaScript.svg
  assets/assets/svg/languages/Kotlin.svg
  assets/assets/svg/languages/Python.svg
  assets/assets/svg/languages/Scala.svg
  assets/assets/svg/languages/Shell.svg
  assets/assets/svg/languages/Swift.svg
  assets/assets/svg/logo.svg
  assets/assets/svg/mail-alt.svg
  assets/assets/svg/rss.svg
  assets/assets/svg/slideshare.svg
  assets/assets/svg/star.svg
  assets/assets/svg/twitter.svg
  assets/assets/svg/universal-access.svg
  assets/assets/svg/user.svg
  assets/css/article.css
  assets/css/main.css
  assets/img/banners/blocks.jpg
  assets/img/banners/coding.jpg
  assets/img/banners/fence.jpg
  assets/img/banners/laptop.jpg
  assets/img/banners/lights.jpg
  assets/img/banners/zalando-people.jpg
  assets/img/zalando-bullet.png
  assets/svg/down-open.svg
  assets/svg/facebook.svg
  assets/svg/gplus.svg
  assets/svg/linkedin.svg
  assets/svg/reddit-alien.svg
  assets/svg/up-open.svg
Labels: e: Community, pr: Work In Progress

#125 Improved page layout
  _includes/footer.html
  _includes/header.html
  _includes/recent-posts.html
  _layouts/article.html
  _pages/index.md
  _pages/projects.md
  assets/css/main.css
Labels: Website, e: Yak Shaving

#133 Docs pages for the website
  _config.yml
  _docs/index.md
  _docs/releasing/license.md
  _docs/using/how-to-oss.md
  _docs/using/rules-of-play.md
  _includes/banner.html
  _includes/docs-list.html
  _includes/header.html
  _includes/history.html
  _layouts/default.html
  _layouts/documentation.html
  _pages/index.md
  assets/css/article.css
  assets/js/index.js
Labels: Website, e: Yak Shaving
