Repository zalando/zalando.github.io, pull requests merged in 2018-04, with the labels that each got.

#10 Initial jekyll setup. Fixes #9
  .gitignore
  404.html
  Gemfile
  Gemfile.lock
  _config.yml
  about.md
  index.md
Labels: e: Yak Shaving, website

#15 Contributing doc. Fixes #14
  CONTRIBUTING.md
Labels: e: Yak Shaving, pr: Needs a Review

#17 PR template doc. Fixes #16
  .github/PULL_REQUEST_TEMPLATE.md
Labels: e: Yak Shaving, pr: Needs a Review

#22 Added some new features to the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr: Needs a Review

#23 renamed codeowners.md to codeowners
  .github/CODEOWNERS
Labels: pr: Needs a Review

#52 PR template updated
  .github/PULL_REQUEST_TEMPLATE.md
Labels: e: Yak Shaving

#51 Contributing document updates
  CONTRIBUTING.md
Labels: e: Yak Shaving

#18 Website layout. Fixes #3
  .gitignore
  assets/css/main.css
  assets/img/zalando-people.jpg
  assets/img/zalando.ico
  assets/js/index.js
  assets/js/project.js
  assets/js/statistic.js
  assets/js/user.js
  assets/svg/gg.svg
  assets/svg/handshake-o.svg
  assets/svg/languages/Go.svg
  assets/svg/languages/Java.svg
  assets/svg/languages/Javascript.svg
  assets/svg/languages/Python.svg
  assets/svg/languages/Scala.svg
  assets/svg/languages/Swift.svg
  assets/svg/logo--no-text.svg
  assets/svg/logo.svg
  assets/svg/mail-alt.svg
  assets/svg/rss.svg
  assets/svg/slideshare.svg
  assets/svg/twitter.svg
  assets/svg/universal-access.svg
  index.html
  package-lock.json
  package.json
Labels: e: Yak Shaving, website

#53 Updating Readme
  MAINTAINERS
  README.md
  SECURITY.md
Labels: e: Yak Shaving

#56 Remove extra whitespace
  CONTRIBUTING.md
Labels: e: Yak Shaving

#61 issue template update
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: e: Yak Shaving
